version: '3.7'
services:
  kener:
    build: .
    container_name: kener
    environment:
      - TZ=Etc/CET
      #- GH_TOKEN=
      #- API_TOKEN=
      #- API_IP=

      #- PORT=3000 Port app listens on IN CONTAINER

      ### If any of the below are changed make sure the bound volume is correct as well ###
      #- CONFIG_DIR=/config
      #- PUBLIC_KENER_FOLDER=/static/kener
      #- MONITOR_YAML_PATH=/config/monitors.yaml
      #- SITE_YAML_PATH=/config/site.yaml

    ports:
      - '3000:3000/tcp'
